//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OlyMath.Trainee
{
    public partial class ViewModule
    {
        protected global::System.Web.UI.WebControls.Literal litModuleTitle;
        protected global::System.Web.UI.WebControls.Literal litModuleDesc;
        protected global::System.Web.UI.WebControls.Repeater rptMaterials;
        protected global::System.Web.UI.WebControls.Repeater rptAssessments;
        protected global::System.Web.UI.WebControls.Label lblNoMaterials;
    }
}