// <auto-generated />
namespace WAPP_Assignment_Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddModuleChapter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddModuleChapter));
        
        string IMigrationMetadata.Id
        {
            get { return "202605200835327_AddModuleChapter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
